import { AppProvider } from "@/Contexts/AppContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Common/Header";
import Footer from "@/components/Common/Footer";
import { Toaster } from "sonner";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <head>
        <title>Next.js App</title>
      </head> */}
      <body className="min-h-full flex flex-col">
        <AppProvider>
          <Toaster />
          <Header />
          <main className="flex-grow bg-[url('/tableye.png')]">{children}</main>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
